# Identificación del proyecto
sonar.projectKey= spring-petclinic-frontend
sonar.projectName= spring-petclinic-frontend
sonar.login= sqp_db964732d125bd29c6e9f5f1ddc485a1d72b3a99
sonar.host.url=http://localhost:9000

# Dónde está el código
sonar.sources=src
sonar.tests=src

# Exclusiones (para que no analice librerías externas ni tests como código)
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.test.inclusions=**/*.spec.ts

# Ruta del reporte de cobertura (Angular usa LCOV, no Jacoco)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
